import { EHeroClass, IUnit } from "../types";

export const CAMERA_MAX_HEIGHT = 800;
export const ROOM_WIDTH = 1600;
export const ROOM_OBJECT_POSITION = 200;
export const GROUND_HEIGHT = 150;
export const ROOM_HEIGHT = 600;
export const INVENTORY_HEIGHT = 100;
export const FLOOR_HEIGHT = GROUND_HEIGHT + ROOM_HEIGHT;
export const DUDES_DISTANCE = 250; // distance between two dudes in queue
export const floorY = [FLOOR_HEIGHT * 3, FLOOR_HEIGHT * 2, FLOOR_HEIGHT];
export const STAIR_MOVE_SPEED_BOOST = 10;
export const FALL_MOVE_SPEED_BOOST = 10;

export const TAKE_ITEM_ANIMATION_TIME = 1200;
export const USE_ITEM_ANIMATION_TIME = 1000;
export const USE_ROOM_OBJECT_ANIMATION_TIME = 1000;

export const MAX_DUDE_HP = 4;

export const DUDES_MOVE_SPEED = 50;
export const DUDES_MOVE_SPEED_BOOST = 300;

const CAMERA_SPEED_PARAM = 0.01625;
export const CAMERA_MOVE_SPEED = DUDES_MOVE_SPEED * CAMERA_SPEED_PARAM;

export const DUDE_REVIVE_TIME = 10000;

export const DUDE_IS_CURSED_TIME = 15000;

export const DUDE_IS_STUNNED_TIME = 3000;

export const ANIMATION_COMPLETE = "animationcomplete";

// INVENTORY

export const BAG_OPEN_CD = 10000;
export const SWORD_ATTACK_CD = 10000;
export const STONE_HEAVY_DROP_CD = 10000;
export const CURSED_SKULL_BOMB_CD = 11000;
export const CURSED_SKULL_BLOCK_CD = 15000;
export const MAX_CURSE_POWER = 0;

// IMAGES

// IMAGES - BACKGROUNDS

export const IMAGE_LOBBY_LOADING = "IMAGE_LOBBY_LOADING";
export const IMAGE_LOBBY_FOX_SMILE = "IMAGE_LOBBY_FOX_SMILE";
export const IMAGE_MAIN_MENU = "IMAGE_MAIN_MENU";

// IMAGES - CHARACTERS

// export const IMAGE_CHARACTER_BEAR_RIGHT = "IMAGE_CHARACTER_BEAR_RIGHT";

// CHARACTERS - GENERAL
export const IMAGE_STONE_FROM_TOP = "IMAGE_STONE_FROM_TOP";

// WOLF
export const IMAGE_WOLF_WALK = "IMAGE_WOLF_WALK";
export const IMAGE_WOLF_GHOST = "IMAGE_WOLF_GHOST";
export const IMAGE_WOLF_PAIN = "IMAGE_WOLF_PAIN";
export const IMAGE_WOLF_DAGGER = "IMAGE_WOLF_DAGGER";
export const IMAGE_WOLF_TAKE = "IMAGE_WOLF_TAKE";
export const IMAGE_WOLF_HEAD_LEFT = "IMAGE_WOLF_HEAD_LEFT";
export const IMAGE_WOLF_HEAD_UP = "IMAGE_WOLF_HEAD_UP";
export const IMAGE_WOLF_USE_STONE = "IMAGE_WOLF_USE_STONE";
export const IMAGE_WOLF_USE_HP_BOTTLE = "IMAGE_WOLF_USE_HP_BOTTLE";
export const IMAGE_WOLF_USE_ROOM_OBJECT = "IMAGE_WOLF_USE_ROOM_OBJECT";
export const IMAGE_WOLF_USE_SKULL = "IMAGE_WOLF_USE_SKULL";
export const IMAGE_WOLF_FALL = "IMAGE_WOLF_FALL";
export const IMAGE_WOLF_WALK_CURSED = "IMAGE_WOLF_WALK_CURSED";
export const IMAGE_WOLF_CORPSE = "IMAGE_WOLF_CORPSE";

// FOX
export const IMAGE_FOX_WALK = "IMAGE_FOX_WALK";
export const IMAGE_FOX_TAKE = "IMAGE_FOX_TAKE";
export const IMAGE_FOX_GHOST = "IMAGE_FOX_GHOST";
export const IMAGE_FOX_DAGGER = "IMAGE_FOX_DAGGER";
export const IMAGE_FOX_PAIN = "IMAGE_FOX_PAIN";
export const IMAGE_FOX_FALL = "IMAGE_FOX_FALL";
export const IMAGE_FOX_CORPSE = "IMAGE_FOX_CORPSE";
export const IMAGE_FOX_USE_ROOM_OBJECT = "IMAGE_FOX_USE_ROOM_OBJECT";
export const IMAGE_FOX_USE_HP_BOTTLE = "IMAGE_FOX_USE_HP_BOTTLE";
export const IMAGE_FOX_HEAD_LEFT = "IMAGE_FOX_HEAD_LEFT";
export const IMAGE_FOX_USE_STONE = "IMAGE_FOX_USE_STONE";
export const IMAGE_FOX_HEAD_UP = "IMAGE_FOX_HEAD_UP";
export const IMAGE_FOX_USE_SKULL = "IMAGE_FOX_USE_SKULL";
export const IMAGE_FOX_WALK_CURSED = "IMAGE_FOX_WALK_CURSED";

// PIG
export const IMAGE_PIG_WALK = "IMAGE_PIG_WALK";
export const IMAGE_PIG_GHOST = "IMAGE_PIG_GHOST";
export const IMAGE_PIG_PAIN = "IMAGE_PIG_PAIN";
export const IMAGE_PIG_DAGGER = "IMAGE_PIG_DAGGER";
export const IMAGE_PIG_APPEAR = "IMAGE_PIG_APPEAR";
export const IMAGE_PIG_APPEAR_NEXT = "IMAGE_PIG_APPEAR_NEXT";
export const IMAGE_PIG_FALL = "IMAGE_PIG_FALL";
export const IMAGE_PIG_CORPSE = "IMAGE_PIG_CORPSE";
export const IMAGE_PIG_TAKE = "IMAGE_PIG_TAKE";
export const IMAGE_PIG_HEAD_LEFT = "IMAGE_PIG_HEAD_LEFT";
export const IMAGE_PIG_USE_STONE = "IMAGE_PIG_USE_STONE";
export const IMAGE_PIG_USE_HP_BOTTLE = "IMAGE_PIG_USE_HP_BOTTLE";
export const IMAGE_PIG_USE_SKULL = "IMAGE_PIG_USE_SKULL";
export const IMAGE_PIG_USE_ROOM_OBJECT = "IMAGE_PIG_USE_ROOM_OBJECT";
export const IMAGE_PIG_HEAD_UP = "IMAGE_PIG_HEAD_UP";
export const IMAGE_PIG_WALK_CURSED = "IMAGE_PIG_WALK_CURSED";

// BEAR
export const IMAGE_BEAR_WALK = "IMAGE_BEAR_WALK";
export const IMAGE_BEAR_WALK_CURSED = "IMAGE_BEAR_WALK_CURSED";
export const IMAGE_BEAR_TAKE = "IMAGE_BEAR_TAKE";
export const IMAGE_BEAR_GHOST = "IMAGE_BEAR_GHOST";
export const IMAGE_BEAR_CORPSE = "IMAGE_BEAR_CORPSE";
export const IMAGE_BEAR_PAIN = "IMAGE_BEAR_PAIN";
export const IMAGE_BEAR_DAGGER = "IMAGE_BEAR_DAGGER";
//export const IMAGE_BEAR_THROW_SKULL = "IMAGE_BEAR_THROW_SKULL";
//export const IMAGE_BEAR_THROW_SKULL_2 = "IMAGE_BEAR_THROW_SKULL_2";
export const IMAGE_BEAR_HEAD_UP = "IMAGE_BEAR_HEAD_UP";
export const IMAGE_BEAR_USE_STONE = "IMAGE_BEAR_USE_STONE";
export const IMAGE_BEAR_USE_SKULL = "IMAGE_BEAR_USE_SKULL";
export const IMAGE_BEAR_USE_ROOM_OBJECT = "IMAGE_BEAR_USE_ROOM_OBJECT";
export const IMAGE_BEAR_USE_HP_BOTTLE = "IMAGE_BEAR_USE_HP_BOTTLE";
export const IMAGE_BEAR_HEAD_LEFT = "IMAGE_BEAR_HEAD_LEFT";
export const IMAGE_BEAR_FALL = "IMAGE_BEAR_FALL";

// ROOM OBJECTS
export const IMAGE_ROOM_OBJECT_BAT = "IMAGE_ROOM_OBJECT_BAT";
export const IMAGE_ROOM_OBJECT_TRAP = "IMAGE_ROOM_OBJECT_TRAP";
export const IMAGE_ROOM_OBJECT_SKULL_PILE = "IMAGE_ROOM_OBJECT_SKULL_PILE";
export const IMAGE_RIDDLE_ROOM_OBJECT = "IMAGE_RIDDLE_ROOM_OBJECT";
export const IMAGE_RIDDLE_ROOM_OBJECT_CLOSED = "IMAGE_RIDDLE_ROOM_OBJECT_CLOSED";
export const IMAGE_WALL_DOOR = "IMAGE_WALL_DOOR";
export const IMAGE_WALL_DOOR_OPEN = "IMAGE_WALL_DOOR_OPEN";
export const IMAGE_CHEST = "IMAGE_CHEST";
export const IMAGE_ROOM_OBJECT_GHOST_BEHIND = "IMAGE_ROOM_OBJECT_GHOST_BEHIND";
export const IMAGE_ROOM_OBJECT_GHOST_FRONT = "IMAGE_ROOM_OBJECT_GHOST_FRONT";
export const IMAGE_ROOM_OBJECT_SPIDER = "IMAGE_ROOM_OBJECT_SPIDER";

export const IMAGE_HOME_TP_DOOR = "IMAGE_HOME_TP_DOOR";
export const IMAGE_ESCAPE_DOOR = "IMAGE_ESCAPE_DOOR";
export const IMAGE_LADDER = "IMAGE_LADDER";
export const IMAGE_ROOM_OBJECT_BARREL = "IMAGE_ROOM_OBJECT_BARREL";
export const IMAGE_ROOM_OBJECT_BOOKS = "IMAGE_ROOM_OBJECT_BOOKS";
export const IMAGE_ROOM_OBJECT_SWORDS = "IMAGE_ROOM_OBJECT_SWORDS";
export const IMAGE_ROOM_OBJECT_STONES = "IMAGE_ROOM_OBJECT_STONES";
export const IMAGE_ROOM_OBJECT_STONES_2 = "IMAGE_ROOM_OBJECT_STONES_2";
export const IMAGE_ROOM_OBJECT_STONES_3 = "IMAGE_ROOM_OBJECT_STONES_3";
export const IMAGE_ROOM_OBJECT_BUCKET = "IMAGE_ROOM_OBJECT_BUCKET";

// ITEMS

export const IMAGE_ITEM_BAG = "IMAGE_ITEM_BAG";
export const IMAGE_ITEM_CANDLE = "IMAGE_ITEM_CANDLE";
export const IMAGE_ITEM_DAGGER = "IMAGE_ITEM_DAGGER";
export const IMAGE_ITEM_GOLDEN_SKULL = "IMAGE_ITEM_GOLDEN_SKULL";
export const IMAGE_ITEM_BOMB_SKULL = "IMAGE_ITEM_BOMB_SKULL";
export const IMAGE_ITEM_BLOCK_SKULL = "IMAGE_ITEM_BLOCK_SKULL";
export const IMAGE_INVENTORY_SLOT = "IMAGE_INVENTORY_SLOT";
export const IMAGE_ITEM_KEY = "IMAGE_ITEM_KEY";
export const IMAGE_ITEM_KEY_DISABLED = "IMAGE_ITEM_KEY_DISABLED";
export const IMAGE_ITEM_HP_BOTTLE = "IMAGE_ITEM_HP_BOTTLE";
export const IMAGE_ITEM_HP_BOTTLE_DISABLED = "IMAGE_ITEM_HP_BOTTLE_DISABLED";
export const IMAGE_ITEM_HP_HOME_TP = "IMAGEY_ITEM_HP_HOME_TP";
export const IMAGE_ITEM_HP_HOME_TP_DISABLED = "IMAGEY_ITEM_HP_HOME_TP_DISABLED";
export const IMAGE_ITEM_LIGHT_BOTTLE = "IMAGE_ITEM_LIGHT_BOTTLE";
export const IMAGE_ITEM_LIGHT_BOTTLE_DISABLED = "IMAGE_ITEM_LIGHT_BOTTLE_DISABLED";
export const IMAGE_ITEM_SHIELD = "IMAGE_ITEM_SHIELD";
export const IMAGE_ITEM_SKULL = "IMAGE_ITEM_SKULL";
export const IMAGE_ITEM_STONE = "IMAGE_ITEM_STONE";
export const IMAGE_ITEM_SKULL_GROUND_1 = "IMAGE_ITEM_SKULL_GROUND_1";
export const IMAGE_ITEM_SKULL_GROUND_2 = "IMAGE_ITEM_SKULL_GROUND_2";
export const IMAGE_ITEM_SKULL_GROUND_3 = "IMAGE_ITEM_SKULL_GROUND_3";
export const IMAGE_ITEM_DAGGER_GROUND = "IMAGE_ITEM_DAGGER_GROUND";
export const IMAGE_ITEM_HP_BOTTLE_GROUND = "IMAGE_ITEM_HP_BOTTLE_GROUND";
export const IMAGE_ITEM_SHIELD_GROUND = "IMAGE_ITEM_SHIELD_GROUND";
export const IMAGE_ITEM_STONE_GROUND = "IMAGE_ITEM_STONE_GROUND";

// UI

export const IMAGE_UI_CURSE_BOOK = "IMAGE_UI_CURSE_BOOK";
export const IMAGE_UI_BUTTON_Q = "IMAGE_UI_BUTTON_Q";
export const IMAGE_UI_BUTTON_W = "IMAGE_UI_BUTTON_W";
export const IMAGE_UI_BUTTON_E = "IMAGE_UI_BUTTON_E";
export const IMAGE_UI_BUTTON_R = "IMAGE_UI_BUTTON_R";
export const IMAGE_UI_BUTTON_T = "IMAGE_UI_BUTTON_T";
export const IMAGE_UI_BUTTON_A = "IMAGE_UI_BUTTON_A";
export const IMAGE_UI_BUTTON_S = "IMAGE_UI_BUTTON_S";
export const IMAGE_UI_BUTTON_D = "IMAGE_UI_BUTTON_D";
export const IMAGE_UI_BUTTON_F = "IMAGE_UI_BUTTON_F";
export const IMAGE_UI_BUTTON_Z = "IMAGE_UI_BUTTON_Z";
export const IMAGE_UI_BUTTON_X = "IMAGE_UI_BUTTON_X";
export const IMAGE_UI_BUTTON_C = "IMAGE_UI_BUTTON_C";
export const IMAGE_UI_BUTTON_V = "IMAGE_UI_BUTTON_V";

export const IMAGE_ITEMS_PANEL = "IMAGE_ITEMS_PANEL";
export const IMAGE_RIDDLE_PANEL = "IMAGE_RIDDLE_PANEL";
export const IMAGE_INVENTORY_BG_MID = "IMAGE_INVENTORY_BG_MID";
export const IMAGE_INVENTORY_BG_LEFT = "IMAGE_INVENTORY_BG_LEFT";
export const IMAGE_INVENTORY_BG_LEFT_EMPTY = "IMAGE_INVENTORY_BG_LEFT_EMPTY";
export const IMAGE_INVENTORY_BG_LEFT_SKULL_1 = "IMAGE_INVENTORY_BG_LEFT_SKULL_1";
export const IMAGE_INVENTORY_BG_LEFT_SKULL_2 = "IMAGE_INVENTORY_BG_LEFT_SKULL_2";
export const IMAGE_INVENTORY_BG_LEFT_SKULL_3 = "IMAGE_INVENTORY_BG_LEFT_SKULL_3";
export const IMAGE_INVENTORY_BG_LEFT_SKULL_4 = "IMAGE_INVENTORY_BG_LEFT_SKULL_4";
export const IMAGE_INVENTORY_BG_RIGHT = "IMAGE_INVENTORY_BG_RIGHT";
export const IMAGE_INVENTORY_VERTICAL_LINE = "IMAGE_INVENTORY_VERTICAL_LINE";
export const IMAGE_COMPONENT_SLOT = "IMAGE_COMPONENT_SLOT";
export const IMAGE_BONUS_PANEL = "IMAGE_BONUS_PANEL";
export const IMAGE_CRAFT_TABLE = "IMAGE_CRAFT_TABLE";
export const IMAGE_BUTTON_CRAFT = "IMAGE_BUTTON_CRAFT";
export const IMAGE_BUTTON_CROSS = "IMAGE_BUTTON_CROSS";
export const IMAGE_BUTTON_LEFT = "IMAGE_BUTTON_LEFT";
export const IMAGE_BUTTON_RIGHT = "IMAGE_BUTTON_RIGHT";
export const IMAGE_LOBBY_CHARACTER_BEAR = "IMAGE_LOBBY_CHARACTER_BEAR";
export const IMAGE_LOBBY_CHARACTER_FOX = "IMAGE_LOBBY_CHARACTER_FOX";
export const IMAGE_LOBBY_CHARACTER_PIG = "IMAGE_LOBBY_CHARACTER_PIG";
export const IMAGE_LOBBY_CHARACTER_WOLF = "IMAGE_LOBBY_CHARACTER_WOLF";
export const IMAGE_LOBBY_CHARACTER_BLACK_BEAR = "IMAGE_LOBBY_CHARACTER_BLACK_BEAR";
export const IMAGE_LOBBY_CHARACTER_BLACK_FOX = "IMAGE_LOBBY_CHARACTER_BLACK_FOX";
export const IMAGE_LOBBY_CHARACTER_BLACK_PIG = "IMAGE_LOBBY_CHARACTER_BLACK_PIG";
export const IMAGE_LOBBY_CHARACTER_BLACK_WOLF = "IMAGE_LOBBY_CHARACTER_BLACK_WOLF";
export const IMAGE_LOBBY_CHAR_ACTIVE = "IMAGE_LOBBY_CHAR_ACTIVE";
export const IMAGE_CHARACTER_CURSE_SELECTED = "IMAGE_CHARACTER_CURSE_SELECTED";
export const IMAGE_UI_HP_HEART = "IMAGE_UI_HP_HEART";
export const IMAGE_UI_CURSED_ITEM_EFFECT = "IMAGE_UI_CURSED_ITEM_EFFECT";

export const IMAGE_UI_BONUS_HEAL = "IMAGE_UI_BONUS_HEAL";
export const IMAGE_UI_BONUS_HP = "IMAGE_UI_BONUS_HP";
export const IMAGE_UI_BONUS_ITEM_SHIELD = "IMAGE_UIIMAGE_UI_BONUS_ITEM_SHIELD_BONUS_HEAL";
export const IMAGE_UI_BONUS_REMOVE_CURSE = "IMAGE_UI_BONUS_REMOVE_CURSE";
export const IMAGE_UI_ITEM_SLOT_CURSED_BG = "IMAGE_UI_ITEM_SLOT_CURSED_BG";

export const IMAGE_UI_BONUS_SLOT_SELECTED_1 = "IMAGE_UI_BONUS_SLOT_SELECTED_1";
export const IMAGE_UI_BONUS_SLOT_SELECTED_2 = "IMAGE_UI_BONUS_SLOT_SELECTED_2";

// FIRST PLAN OBJECTS

export const IMAGE_FIRSTPLAN_BAT = "IMAGE_FIRSTPLAN_BAT";
export const IMAGE_FIRSTPLAN_CHAIN = "IMAGE_FIRSTPLAN_CHAIN";
export const IMAGE_FIRSTPLAN_CHAIN_SMALL = "IMAGE_FIRSTPLAN_CHAIN_SMALL";
export const IMAGE_FIRSTPLAN_STONE = "IMAGE_FIRSTPLAN_STONE";
export const IMAGE_FIRSTPLAN_SPIDER = "IMAGE_FIRSTPLAN_SPIDER";
export const IMAGE_FIRSTPLAN_COLUMN = "IMAGE_FIRSTPLAN_COLUMN";
export const IMAGE_FIRSTPLAN_WATER_DROP = "IMAGE_FIRSTPLAN_WATER_DROP";
export const IMAGE_FIRSTPLAN_ROCK = "IMAGE_FIRSTPLAN_ROCK";
export const IMAGE_FIRSTPLAN_BAT_GIANT = "IMAGE_FIRSTPLAN_BAT_GIANT";
export const IMAGE_FIRSTPLAN_WEB = "IMAGE_FIRSTPLAN_WEB";
export const IMAGE_FIRSTPLAN_WITCH = "IMAGE_FIRSTPLAN_WITCH";

// CURSE EFFECTS

export const IMAGE_CURSE_FOG = "IMAGE_CURSE_FOG";
export const IMAGE_CURSE_SLOT_CLOSED = "IMAGE_CURSE_SLOT_CLOSED";
export const IMAGE_CURSE_SLOT_WEB = "IMAGE_CURSE_SLOT_WEB";

// SOUNDS

export const SOUND_WOOD_1 = "SOUND_WOOD_1";
export const SOUND_WOOD_2 = "SOUND_WOOD_2";
export const SOUND_WOOD_3 = "SOUND_WOOD_3";
export const SOUND_WOOD_4 = "SOUND_WOOD_4";
export const SOUND_WOOD_5 = "SOUND_WOOD_5";
// ROOM OBJECTS
export const SOUND_USE_CHEST = "SOUND_USE_CHEST";
export const SOUND_USE_CHEST_LOCKED = "SOUND_USE_CHEST_LOCKED";
export const SOUND_USE_CURSED_CHEST = "SOUND_USE_CURSED_CHEST";
export const SOUND_USE_BAT_ATTACK = "SOUND_USE_BAT_ATTACK";
export const SOUND_USE_SKULL_PILE = "SOUND_USE_SKULL_PILE";
export const SOUND_TRIGGER_BAT_ATTACK = "SOUND_TRIGGER_BAT_ATTACK";
export const SOUND_TRIGGER_GHOST_BEHIND = "SOUND_TRIGGER_GHOST_BEHIND";
export const SOUND_RO_SPIDER = "SOUND_RO_SPIDER";
// ITEM
export const SOUND_TAKE_ITEM = "SOUND_TAKE_ITEM";
export const SOUND_TAKE_ITEM_HP_BOTTLE = "SOUND_TAKE_ITEM_HP_BOTTLE";
export const SOUND_USE_ITEM_DAGGER = "SOUND_USE_ITEM_DAGGER";
export const SOUND_TAKE_ITEM_KEY = "SOUND_TAKE_ITEM_KEY";
export const SOUND_TAKE_ITEM_DAGGER = "SOUND_TAKE_ITEM_DAGGER";
export const SOUND_TAKE_ITEM_STONE_LIGHT = "SOUND_TAKE_ITEM_STONE_LIGHT";
export const SOUND_TAKE_ITEM_STONE_HEAVY = "SOUND_TAKE_ITEM_STONE_HEAVY";
export const SOUND_TAKE_ITEM_SHIELD = "SOUND_TAKE_ITEM_SHIELD";
export const SOUND_TAKE_ITEM_SKULL = "SOUND_TAKE_ITEM_SKULL";
export const SOUND_USE_ITEM_HP_BOTTLE = "SOUND_USE_ITEM_HP_BOTTLE";
export const SOUND_USE_ITEM_HP_BOTTLE_2 = "SOUND_USE_ITEM_HP_BOTTLE_2";
export const SOUND_USE_ITEM_STONE = "SOUND_USE_ITEM_STONE";
export const SOUND_USE_ITEM_STONE_2 = "SOUND_USE_ITEM_STONE_2";
export const SOUND_USE_ITEM_SKULL_BEAR = "SOUND_USE_ITEM_SKULL_BEAR";
// DUDE
export const SOUND_DUDE_WOLF_HURT = "SOUND_DUDE_WOLF_HURT";
export const SOUND_DUDE_PIG_HURT = "SOUND_DUDE_PIG_HURT";
export const SOUND_DUDE_BEAR_HURT = "SOUND_DUDE_BEAR_HURT";
export const SOUND_DUDE_FOX_HURT = "SOUND_DUDE_FOX_HURT";
export const SOUND_DUDE_APPLY_CURSE = "SOUND_DUDE_APPLY_CURSE";
// UI
export const SOUND_UI_OPEN_CURSE_BOOK = "SOUND_UI_OPEN_CURSE_BOOK";
export const SOUND_MAIN_MENU_START = "SOUND_MAIN_MENU_START";
export const SOUND_MAIN_MENU_CLICK = "SOUND_MAIN_MENU_CLICK";
export const SOUND_MAIN_MENU_CLICK_2 = "SOUND_MAIN_MENU_CLICK_2";
export const SOUND_UI_CLICK_3 = "SOUND_UI_CLICK_3";
export const SOUND_UI_CLICK_4 = "SOUND_UI_CLICK_4";
export const SOUND_UI_CLICK_6 = "SOUND_UI_CLICK_6";

export const SOUND_MAIN_MENU_MUSIC = "SOUND_MAIN_MENU_MUSIC";
export const SOUND_MAIN_MENU_CHANGE_SCENE = "SOUND_MAIN_MENU_CHANGE_SCENE";

export const colors = {
    BLACK: 0x000000,
    BLUE: 0x333399,
    GREY: 0x666666,
    GREEN: 0x339933,
    WHITE: 0x999999,
    GREY_HOVER: 0x888888,
    GREEN_HOVER: 0x22aa22,
    RED: 0xcc4444,
    WHITE_HOVER: 0xbbbbbb,
};
